-- Preserve the farm block table exactly as recorded in the workbook. Blank workbook
-- cells remain NULL so administrators can complete them later without inferred data.

ALTER TABLE farm_blocks ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE farm_blocks ADD COLUMN IF NOT EXISTS early_block_classification text;
ALTER TABLE farm_blocks ADD COLUMN IF NOT EXISTS year_planted integer;

ALTER TABLE farm_blocks ALTER COLUMN forecast_yield_kg DROP DEFAULT;
ALTER TABLE farm_blocks ALTER COLUMN forecast_yield_kg DROP NOT NULL;
ALTER TABLE farm_blocks ALTER COLUMN fruit_fly_pressure DROP DEFAULT;
ALTER TABLE farm_blocks ALTER COLUMN fruit_fly_pressure DROP NOT NULL;
ALTER TABLE farm_blocks ALTER COLUMN disease_rating DROP DEFAULT;
ALTER TABLE farm_blocks ALTER COLUMN disease_rating DROP NOT NULL;

ALTER TABLE farm_blocks DROP CONSTRAINT IF EXISTS farm_blocks_year_planted_check;
ALTER TABLE farm_blocks ADD CONSTRAINT farm_blocks_year_planted_check
  CHECK (year_planted IS NULL OR year_planted BETWEEN 1900 AND 2200) NOT VALID;

WITH exact_block (
  farm_code, block_code, description, early_block_classification,
  shoot_maturity, fruit_fly_pressure, disease_rating
) AS (
  VALUES
    ('FARM-LAND-A', 'A1', 'Farm close to the road. It boarders the Cashew Farm', 'Yes', 1.0::real, 'Medium', 'Medium'),
    ('FARM-LAND-A', 'A2', 'Where Ante Mansa Farms', 'Mid', 0.7::real, 'Medium', 'Medium'),
    ('FARM-LAND-A', 'A3', 'Togbuis farming area', 'Mid', 0.7::real, 'Medium', 'Medium'),
    ('FARM-LAND-A', 'A4', 'Land Purchased from Amoateng', 'New', 0.0::real, 'Medium', 'Medium'),
    ('FARM-LAND-A', 'A5', 'New', 'New', 0.0::real, 'NA', 'NA'),
    ('FARM-LAND-B', 'B1', 'Osofo''s Farms', 'Mid', 0.7::real, 'Medium', 'Medium'),
    ('FARM-LAND-B', 'B2', 'Ananes Farms', 'Mid', 0.5::real, 'Medium', 'Medium'),
    ('FARM-LAND-B', 'B3', 'Kwaku Boakyes Farm', 'Mid', 0.6::real, 'Medium', 'Medium'),
    ('FARM-LAND-B', 'B4', 'Where the Oil Palm is', 'New', 0.0::real, 'Medium', 'Medium'),
    ('FARM-LAND-B', 'B5', 'Kwasi Boakyes kids', 'New', 0.0::real, NULL, NULL)
)
UPDATE farm_blocks block
SET description = exact_block.description,
    early_block_classification = exact_block.early_block_classification,
    early_harvest = exact_block.early_block_classification = 'Yes',
    shoot_maturity = exact_block.shoot_maturity,
    year_planted = NULL,
    size_acres = NULL,
    variety = NULL,
    forecast_yield_kg = NULL,
    fruit_fly_pressure = exact_block.fruit_fly_pressure,
    disease_rating = exact_block.disease_rating,
    soil_notes = NULL,
    planting_started_on = NULL,
    status = 'active',
    source = 'Farm Management  Data Records.xlsx',
    updated_at = now()
FROM exact_block
JOIN farms farm ON farm.farm_code = exact_block.farm_code
WHERE block.farm_id = farm.id
  AND block.block_code = exact_block.block_code;

-- The earlier import created zero-count variety rows for blank Variety/Tree cells.
-- Close only those empty inferred rows; real inventory records remain untouched.
UPDATE block_crop_inventories inventory
SET effective_to = CURRENT_DATE,
    updated_at = now()
FROM farm_blocks block
JOIN farms farm ON farm.id = block.farm_id
WHERE inventory.block_id = block.id
  AND inventory.effective_to IS NULL
  AND inventory.total_trees = 0
  AND inventory.productive_trees = 0
  AND inventory.non_productive_trees = 0
  AND inventory.dead_trees = 0
  AND farm.farm_code IN ('FARM-LAND-A', 'FARM-LAND-B')
  AND block.block_code IN ('A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'B1', 'B2', 'B3', 'B4', 'B5');

-- A6 was generated by a routine check, but the supplied Farm Land A table ends at A5.
-- Keep it as archived history instead of exposing it as a current workbook block.
UPDATE farm_blocks block
SET status = 'archived',
    updated_at = now()
FROM farms farm
WHERE block.farm_id = farm.id
  AND farm.farm_code = 'FARM-LAND-A'
  AND block.block_code = 'A6'
  AND block.status <> 'archived';

INSERT INTO block_status_history (
  id, block_id, action, previous_status, new_status, reason, effective_date, performed_by
)
SELECT
  'xlsx-2026-block-a6-archive', block.id, 'archived', 'active', 'archived',
  'Excluded from the current profile because the supplied Farm Land A table ends at A5.',
  CURRENT_DATE, NULL
FROM farm_blocks block
JOIN farms farm ON farm.id = block.farm_id
WHERE farm.farm_code = 'FARM-LAND-A' AND block.block_code = 'A6'
ON CONFLICT (id) DO NOTHING;
