import { useCallback, useEffect, useState } from 'react';
import { base44 } from '@/api/base44Client';
import { subscribeToDataChanges } from '@/lib/data-sync';
import { Plus, FileText, TriangleAlert, RefreshCw, CircleCheck, Clock, ChartNoAxesColumnIncreasing, MapPin, ArrowRight, MoreHorizontal, ChevronRight, SlidersHorizontal, Users, Landmark, Tag } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import './issues.css';
import { latestIssuesFirst, issueReportStamp } from '@/lib/issue-report-time';
import { loadIssues, saveIssues } from '@/lib/issues-storage';
import ReportIssueDialog from '@/components/farm/ReportIssueDialog';
import { FARM_SCOPE_OPTIONS, matchesFarmScope } from '@/lib/farm-scope';
const seed=[['ISS-2026-021','Irrigation pressure too low','Water / Irrigation','Farm A / A2','High','Kwame Mensah','2026-10-15','In Progress'],['ISS-2026-020','Anthracnose symptoms observed','Pest & Disease','Farm B / B3','Critical','Grace Ofori','2026-10-12','Action Required'],['ISS-2026-019','Fertilizer stock below threshold','Inventory','Farm A / Store','Medium','Esther Dapaah','2026-10-18','Open'],['ISS-2026-018','Harvest crates damaged','Tools & Equipment','Farm B / B1','Low','Kojo Mensah','2026-10-20','Open'],['ISS-2026-017','Delayed transport from packing house','Logistics','Farm B / Packing House','High','James Mensah','2026-10-14','In Progress']].map(([id,title,category,farm,severity,owner,due,status])=>({id,title,category,farm,severity,owner,due,status}));
const closed=[['ISS-2026-014','Broken irrigation valve','Farm A / A1','Valve replaced and tested','Maintenance Team','08 Oct 2026','GH₵ 480'],['ISS-2026-012','Sprayer nozzle blockage','Farm B / B2','Nozzle replaced','Kojo Mensah','07 Oct 2026','GH₵ 95'],['ISS-2026-010','Low cold-room temperature stability','Packing House','Thermostat recalibrated','Bright Mechanics','05 Oct 2026','GH₵ 650']];
const categories=[['Pest & Disease',6,'#ff555e'],['Irrigation',4,'#328cff'],['Tools & Equipment',3,'#ffbd38'],['Logistics',3,'#a346fa'],['Inventory',2,'#4aa76a'],['Workforce / Safety',2,'#84939b'],['Harvesting',0,'#d97706'],['Planting',0,'#15803d']];
const farms=[['Farm A / A1',2,1,1,0],['Farm A / A2',3,1,1,1],['Farm B / B1',2,0,1,1],['Farm B / B3',4,2,1,1],['Packing House',3,1,1,1]];
const timeline=[['11:40 AM','green','Corrective action added to ISS-2026-021','Kwame Mensah added a corrective action and attached photos.'],['10:15 AM','red','New disease issue reported at Farm B / B3','Anthracnose symptoms observed on Kent variety.'],['09:20 AM','blue','ISS-2026-018 assigned to Kojo Mensah','New issue has been assigned for investigation.'],['Yesterday','orange','Transport delay escalated to High severity','ISS-2026-017 priority changed from Medium to High.'],['Yesterday','green','Irrigation leak issue marked Resolved','ISS-2026-015 has been closed after repair.']];
const tone=v=>({High:'high',Critical:'critical',Medium:'medium',Low:'green',Open:'slate','In Progress':'blue','Action Required':'orange',Resolved:'green'}[v]||'slate');
const date=v=>new Date(`${v}T12:00:00`).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});
const matchesLocation=(record,selection)=>selection==='Packing House'?String(record.farm||'').includes('Packing House'):matchesFarmScope(record,selection);
function Badge({value,dot}){return <span className={`is-badge is-${tone(value)}`}>{dot&&<i/>}{value}</span>;}
function Panel({title,icon:Icon,onView,children}){return <section className="is-panel"><header><h2><Icon/>{title}</h2><button onClick={onView}>View All <ArrowRight/></button></header>{children}</section>;}
function Table({headers,children}){return <div className="is-table"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;}
export default function Issues(){
 const preview=import.meta.env.DEV;
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true);
 const [severity,setSeverity]=useState(''),[status,setStatus]=useState(''),[farm,setFarm]=useState(''),[category,setCategory]=useState(''),[dialog,setDialog]=useState(null),[view,setView]=useState(null),[error,setError]=useState('');
 const load=useCallback(async()=>{try{setItems(preview?await loadIssues(seed):await base44.entities.Issue.listAll('-created_date'));setError('');}catch(failure){setError(failure.message||'Issues could not be loaded. Please retry.');}finally{setLoading(false);}},[preview]);
 useEffect(()=>{void load();return preview?undefined:subscribeToDataChanges(load,['Issue'],{refreshOnFocus:true});},[load,preview]);
 const filtered=!!(severity||status||farm||category);
 const rows=items.filter(r=>(!severity||r.severity===severity)&&(!status||r.status===status)&&matchesLocation(r,farm)&&(!category||r.category===category));
 const active=rows.filter(r=>!['Resolved','Draft'].includes(r.status)).sort(latestIssuesFirst),reference=preview&&!filtered&&items.length===5;
 const [issuePage,setIssuePage]=useState(1);
 const pageCount=Math.max(1,Math.ceil(active.length/10)),currentPage=Math.min(issuePage,pageCount);
 useEffect(()=>{setIssuePage(1);},[severity,status,farm,category]);
 const categoryRows=categories.map(([name,total,color])=>[name,reference?total:active.filter(r=>r.category===(name==='Irrigation'?'Water / Irrigation':name)).length,color]);
 const farmRows=reference?farms:[...new Set(active.map(r=>r.farm))].map(name=>{const group=active.filter(r=>r.farm===name);return [name,group.length,group.filter(r=>['High','Critical'].includes(r.severity)).length,group.filter(r=>r.severity==='Medium').length,group.filter(r=>r.severity==='Low').length];});
 const resolved=preview?closed.filter(r=>matchesLocation({farm:r[2]},farm)&&!category&&!severity&&(!status||status==='Resolved')):[];
 const metrics=[['Open Issues',FileText,'green',reference?14:active.length,'Issues awaiting resolution'],['High/Critical',TriangleAlert,'red',reference?4:active.filter(r=>['High','Critical'].includes(r.severity)).length,'Require immediate attention'],['In Progress',RefreshCw,'blue',reference?6:active.filter(r=>r.status==='In Progress').length,'Being addressed'],['Resolved This Month',CircleCheck,'green',reference?18:resolved.length+rows.filter(r=>r.status==='Resolved').length,'Closed and verified'],['Overdue Actions',Clock,'orange',reference?3:active.filter(r=>r.due<new Date().toISOString().slice(0,10)).length,'Past due date']];
 const select=(label,value,set,options)=>{const Icon=({'All Severity':SlidersHorizontal,'All Statuses':Users,'All Farms':Landmark,'All Categories':Tag})[label];return <label className="is-select"><Icon/><select aria-label={label} value={value} onChange={e=>set(e.target.value)}><option value="">{label}</option>{options.map(v=><option key={v}>{v}</option>)}</select></label>;};
 const action=r=><button className="is-more" aria-label={`Edit ${r.id}`} onClick={()=>setDialog(r)}><MoreHorizontal/></button>;

 return <div className="issues-dashboard" data-preserve-colors="true">
 <div className="is-filters">{select('All Severity',severity,setSeverity,['High','Critical','Medium','Low'])}{select('All Statuses',status,setStatus,['Open','In Progress','Action Required','Resolved'])}{select('All Farms',farm,setFarm,[...FARM_SCOPE_OPTIONS.map(option=>option.label),'Packing House'])}{select('All Categories',category,setCategory,['Water / Irrigation',...categories.map(r=>r[0]).filter(n=>n!=='Irrigation')])}<button className="is-add" disabled={loading} onClick={()=>setDialog({})}><Plus/>Report New Issue</button></div>
 {loading&&<p role="status">Loading issues…</p>}{error&&<p role="alert">{error} <button onClick={()=>void load()}>Retry</button></p>}
 {error&&<p role="alert">{error}</p>}
 <div className="is-metrics">{metrics.map(([label,Icon,color,value,description])=><section key={label}><span className={`is-icon is-${color}`}><Icon/></span><div><h2>{label}</h2><strong className={`is-number is-${color}`}>{value}</strong><p>{description}</p></div></section>)}</div>
 <div className="is-middle"><Panel title="Active Issues" icon={ChartNoAxesColumnIncreasing} onView={()=>setView('Active Issues')}><Table headers={['Issue ID','Issue / Challenge','Category','Farm / Block','Severity','Owner','Reported Date','Due Date','Status','Actions']}>{active.slice((currentPage-1)*10,currentPage*10).map(r=><tr key={r.id}><td>{r.issue_code||r.id}</td><td>{r.title}</td><td>{r.category}</td><td>{r.farm}</td><td><Badge value={r.severity} dot/></td><td>{r.owner}</td><td className="is-report-stamp">{issueReportStamp(r)}</td><td>{date(r.due)}</td><td><Badge value={r.status}/></td><td>{action(r)}</td></tr>)}{!active.length&&<tr><td colSpan={10} className="is-empty">No issues match your filters.</td></tr>}</Table><div className="is-pagination"><span>{active.length?`${(currentPage-1)*10+1}–${Math.min(currentPage*10,active.length)} of ${active.length} issues`:'0 issues'}</span><button disabled={currentPage===1} onClick={()=>setIssuePage(currentPage-1)}>Previous</button><span>Page {currentPage} of {pageCount}</span><button disabled={currentPage===pageCount} onClick={()=>setIssuePage(currentPage+1)}>Next</button></div></Panel>
 <Panel title="Recent Issue Activity" icon={Clock} onView={()=>setView('Recent Issue Activity')}><div className="is-timeline">{(preview?timeline:[]).filter(e=>!filtered||rows.some(r=>e.join(' ').includes(r.id))).map(([time,color,title,detail])=><div className="is-event" key={title}><i className={`is-dot is-${color}`}/><time>{time}</time><i className={`is-dot is-${color}`}/><div><strong>{title}</strong><p>{detail}</p></div></div>)}</div></Panel></div>
 <div className="is-bottom"><Panel title="Issues by Category" icon={ChartNoAxesColumnIncreasing} onView={()=>setView('Issues by Category')}><div className="is-categories">{categoryRows.map(([name,total,color])=><button key={name} onClick={()=>setCategory(category===(name==='Irrigation'?'Water / Irrigation':name)?'':name==='Irrigation'?'Water / Irrigation':name)}><span>{name}</span><div><i style={{width:`${total/Math.max(8,...categoryRows.map(r=>r[1]))*100}%`,background:color}}/></div><b>{total}</b></button>)}</div></Panel>
 <Panel title="Issues by Farm / Block" icon={MapPin} onView={()=>setView('Issues by Farm / Block')}><Table headers={['Farm / Block','Open Issues','High/Critical','Medium','Low','Status','']}>{farmRows.map(([name,total,high,medium,low])=><tr key={name}><td>{name}</td><td>{total}</td><td className="is-count-red">{high}</td><td className="is-count-orange">{medium}</td><td className="is-count-green">{low}</td><td><div className="is-stacked" aria-label={`${high} high, ${medium} medium, ${low} low`}><i style={{width:`${high*22}%`,background:'#ff555e'}}/><i style={{width:`${medium*21}%`,background:'#ffc344'}}/><i style={{width:`${low*21}%`,background:'#48a56b'}}/></div></td><td><button aria-label={`View issues at ${name}`} onClick={()=>setFarm(name.includes('Packing House')?'Packing House':FARM_SCOPE_OPTIONS.some(option=>option.label===name.split(' / ').at(-1))?name.split(' / ').at(-1):name.split(' / ')[0])}><ChevronRight/></button></td></tr>)}</Table></Panel></div>
 <Panel title="Recently Resolved Issues" icon={CircleCheck} onView={()=>setView('Recently Resolved Issues')}><Table headers={['Issue ID','Issue','Farm / Block','Resolution','Resolved By','Resolved Date','Cost / Impact','Actions']}>{resolved.map(r=><tr key={r[0]}>{r.map((v,i)=><td key={i}>{v}</td>)}<td><button className="is-more" aria-label={`View ${r[0]}`} onClick={()=>setDialog({resolved:r})}><MoreHorizontal/></button></td></tr>)}{rows.filter(r=>r.status==='Resolved').map(r=><tr key={r.id}><td>{r.issue_code||r.id}</td><td>{r.title}</td><td>{r.farm}</td><td>{r.resolution||'Closed and verified'}</td><td>{r.owner}</td><td>{date(r.due)}</td><td>—</td><td>{action(r)}</td></tr>)}</Table></Panel>
 <Dialog open={!!view} onOpenChange={open=>{if(!open)setView(null);}}><DialogContent className="is-view"><DialogHeader><DialogTitle>{view}</DialogTitle><DialogDescription>Browse the current dashboard selection.</DialogDescription></DialogHeader>{view==='Recent Issue Activity'?<ul>{timeline.filter(()=>preview).map(r=><li key={r[2]}><strong>{r[0]} · {r[2]}</strong><p>{r[3]}</p></li>)}</ul>:view==='Issues by Category'?<ul>{categoryRows.map(r=><li key={r[0]}>{r[0]}: {r[1]}</li>)}</ul>:view==='Issues by Farm / Block'?<ul>{farmRows.map(r=><li key={r[0]}>{r[0]}: {r[1]} open issues</li>)}</ul>:view==='Recently Resolved Issues'?<ul>{resolved.map(r=><li key={r[0]}>{r[0]} · {r[1]} · {r[3]}</li>)}</ul>:<Table headers={['Issue ID','Issue','Farm / Block','Owner','Status','Actions']}>{active.map(r=><tr key={r.id}><td>{r.issue_code||r.id}</td><td>{r.title}</td><td>{r.farm}</td><td>{r.owner}</td><td>{r.status}</td><td>{action(r)}</td></tr>)}</Table>}</DialogContent></Dialog>
 <Dialog open={!!dialog?.resolved} onOpenChange={open=>{if(!open)setDialog(null);}}><DialogContent className="is-dialog"><DialogHeader><DialogTitle>Resolved Issue</DialogTitle><DialogDescription>{dialog?.resolved?.[0]}</DialogDescription></DialogHeader><dl>{['Issue ID','Issue','Farm / Block','Resolution','Resolved By','Resolved Date','Cost / Impact'].map((label,i)=><div key={label}><dt>{label}</dt><dd>{dialog?.resolved?.[i]}</dd></div>)}</dl></DialogContent></Dialog>
 {dialog && !dialog.resolved && <ReportIssueDialog key={dialog.id||'new'} issue={dialog.id?dialog:undefined} issueId={dialog.issue_code||dialog.id||`ISS-2026-${String(Math.max(21,...items.map(r=>Number((r.issue_code||r.id).split('-').at(-1))||0))+1).padStart(3,'0')}`} onClose={()=>setDialog(null)} onSave={async record=>{const next=dialog.id?items.map(item=>item.id===record.id?record:item):[record,...items];if(preview){await saveIssues(next);setItems(next);}else{const payload={...record,issue_code:record.issue_code||record.id};delete payload.id;if(dialog.id){await base44.entities.Issue.update(dialog.id,payload);}else{await base44.entities.Issue.create(payload);}await load();}setDialog(null);}}/>}
 </div>;
}
