import React, { useState } from 'react';
import { Target, FileText, Sprout, TrendingUp, ListChecks, TriangleAlert, Image, MessageSquareText, CalendarDays, UserRound, Pencil, Trash2, X } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { ObjectiveRing } from './ObjectiveOverview';
import './objective-details.css';
const referenceKpis = [
['Harvest Volume (kg)','50,000','42,500',85,'On Track'],['Yield per Hectare (t/ha)','12.0','10.5',88,'On Track'],['Post-Harvest Loss (%)','< 8%','6.5%',81,'On Track'],['Quality Grade A (%)','≥ 90%','97%',97,'On Track'],['Logs Completion Rate','100%','80%',80,'At Risk']
];
function Panel({ icon: Icon, title, action, children }) { return <section className="od-panel"><header><Icon size={19}/><h3>{title}</h3>{action}</header>{children}</section>; }
export default function ObjectiveDetails({ objective: o, preview, onClose, onDelete, onUpdate }) {
 const [tab,setTab] = useState('Overview');
 const reference = preview && o.id === 'preview-1';
 const kpis = reference ? referenceKpis : o.kpis.map(k=>[k.name,String(k.target ?? '—'),String(k.actual ?? '—'),k.achievement,k.achievement >= 100 ? 'On Track' : 'At Risk']);
 const note = o.feedback[0];
 const links = (label, next) => <button className="od-link" onClick={()=>setTab(next)}>{label} →</button>;
 const kpiTable = <div className="od-table-wrap"><table><thead><tr>{['KPI','Target','Current','Progress','Status'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{kpis.map(([name,target,current,progress,status])=><tr key={name}><td>{name}</td><td>{target}</td><td>{current}</td><td><div className="od-kpi-progress"><span>{progress == null ? '—' : `${progress}%`}</span><progress max="100" value={Math.min(100,progress ?? 0)} className={status==='At Risk'?'od-warning':''}/></div></td><td><span className={status==='At Risk'?'od-amber':'od-green'}>● {status}</span></td></tr>)}</tbody></table></div>;
 const activity = <Panel icon={ListChecks} title="Recent Activity Log" action={links('View All Logs','Activity Logs')}><div className="od-record"><CalendarDays size={18}/><div><strong>{reference?'Harvesting log - Block A':o.logs[0]?.title || 'No activity recorded'}</strong>{reference && <><small>2026-10-12 14:20</small><p>Harvested 320 kg of Kent mangoes.<br/>Quality good, no issues.</p><small>👤 Logged by: Kojo Mensah</small></>}</div>{reference && <span className="od-pill">● Synced</span>}</div></Panel>;
 const blocker = <Panel icon={TriangleAlert} title="Blocker / Risk" action={links('View All','Blockers')}><div className="od-record"><TriangleAlert className="od-red" size={18}/><div><strong>{reference?'Irrigation delay in Block C':o.blockers[0]?.name || 'No blocker details recorded'}</strong>{reference && <><small>Reported: 2026-10-11</small><p>Irrigation system maintenance causing delay in harvesting schedule for Block C. Expected to be resolved in 3 days.</p><small>👤 Reported by: Thomas Addo</small></>}</div>{reference && <span className="od-open">Open</span>}</div></Panel>;
 const evidence = <Panel icon={Image} title="Latest Evidence" action={links('View All','Evidence')}>{reference ? <><img className="od-evidence" src="/pages/objectives/harvest-evidence.png" alt="Harvested mangoes in packing crates"/><strong>Harvested mangoes - Block A</strong><small>Uploaded: 2026-10-12 14:35　 By: Kojo Mensah</small></> : <p>{o.evidence.length ? o.evidence[0].name : 'No evidence uploaded.'}</p>}</Panel>;
 const feedback = <div className="od-feedback"><header><MessageSquareText size={20}/><strong>Recent Feedback</strong></header><p>“{reference?'Harvesting is 85% complete. Good progress in Block A and B.':note?.notes || 'No feedback recorded.'}” <span className="od-pill">● Positive</span></p>{note && <small>By {reference?'Emmanuella Adu-boahene':note.author} ・ {reference?'2026-10-12 16:45':note.date}</small>}</div>;
 return <Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent className="objective-details-modal" data-preserve-colors="true"><div className="od-heading"><Target size={35}/><div><DialogTitle>Objective Details</DialogTitle><DialogDescription>{o.name}</DialogDescription></div><DialogClose className="od-header-close" aria-label="Close objective details"><X size={20}/></DialogClose></div><div className="od-scroll"><div className="od-intro"><img src={`/pages/objectives/${/yield/i.test(o.name)?'flowering':/loss/i.test(o.name)?'post-harvest':'harvest'}.png`} alt=""/><div><small>{o.code}　│　{o.category}</small><h2>{o.name}</h2><p className="od-owner"><UserRound size={14}/>{reference?'Emmanuella Adu-boahene':o.owner}<span>│</span><CalendarDays size={14}/> Deadline　{o.end}</p><p>{o.description}</p></div><span className="od-pill">● {o.health}</span></div><div className="od-metrics"><div><ObjectiveRing label="" value={o.outcome}/><section><p>Outcome achievement</p>{reference&&<><b>▲ +12%</b><small>vs. last month</small></>}</section></div><div><ObjectiveRing label="" value={o.execution}/><section><p>Execution progress</p>{reference&&<><b>▲ +8%</b><small>vs. last month</small></>}</section></div><section className="od-counts"><p><FileText size={15}/>{o.kpis.filter(k=>k.achievement>=100).length}/{o.kpis.length} KPIs achieved</p><p><FileText size={15}/>{o.logs.filter(l=>l.status==='Completed').length}/{o.logs.length} logs completed</p><p className="od-red"><TriangleAlert size={15}/>{o.open_blockers} {o.open_blockers===1?'blocker':'blockers'}</p><p>◷　{reference?'Updated 2 hours ago':note?.date || 'No update recorded'}</p></section></div><nav className="od-tabs">{[['Overview','Overview',MessageSquareText],['KPIs',`KPIs (${o.kpis.length})`,TrendingUp],['Activity Logs',`Activity Logs (${reference?12:o.logs.length})`,FileText],['Evidence',`Evidence (${reference?8:o.evidence.length})`,Image],['Notes & Feedback',`Notes & Feedback (${reference?6:o.feedback.length})`,MessageSquareText]].map(([key,label,Icon])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}><Icon size={15}/>{label}</button>)}</nav>
 {tab==='Overview' ? <><div className="od-top-grid"><div><Panel icon={FileText} title="Objective Overview"><p>{o.description} {reference && 'Ensure fruits are harvested at optimal maturity, handled properly, and recorded for full traceability from farm to packing house.'}</p></Panel><Panel icon={Sprout} title="Scope / Contribution"><p>All farms and blocks, with current focus on:</p>{reference ? <ul>{['Block A - Main Orchard (doing well)','Block B - Expansion (on track)','Block C - Irrigation Zone (improving)','Block D - Young Trees','Nursery and Packing House'].map(t=><li key={t}>{t}</li>)}</ul> : <p>{o.contributions.length} farm / block allocations recorded.</p>}</Panel></div><Panel icon={TrendingUp} title="Key Performance Indicators (KPIs)" action={links('View All KPIs','KPIs')}>{kpiTable}</Panel></div><div className="od-bottom-grid">{activity}{blocker}{evidence}</div>{feedback}</> : tab==='KPIs' ? kpiTable : tab==='Evidence' ? evidence : tab==='Notes & Feedback' ? feedback : tab==='Blockers' ? blocker : <>{activity}{!reference&&o.logs.slice(1).map(l=><p key={l.id}>{l.activity_date} ・ {l.title} ・ {l.status}</p>)}</>}
 </div><footer className="od-footer">{preview && <Button className="od-delete" onClick={onDelete}><Trash2 size={15}/>Delete Objective</Button>}<span/><Button variant="outline" onClick={onClose}>Close</Button><Button onClick={onUpdate}><Pencil size={15}/>Update Objective</Button></footer></DialogContent></Dialog>;
}
