import React from 'react';
import { BarChart3, CalendarDays, CheckCircle2, CircleAlert, FileText, Lightbulb, MessageSquareText, Sprout, Target, Trophy, UserRound } from 'lucide-react';
import { previewActivity, previewContributions, previewFeedback } from './objective-preview';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from 'recharts';
import { Button } from '@/components/ui/button';

export const overviewIcons = [Target, CheckCircle2, CircleAlert, CircleAlert, Trophy, CircleAlert];
const percentage = value => value == null ? '—' : `${Math.round(value)}%`;
export function ObjectiveRing({ label, value }) {
  const amount = Math.max(0, Math.min(100, value ?? 0));
  return <div className="objective-ring"><div role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={value == null ? undefined : amount} aria-valuetext={value == null ? 'No result' : percentage(value)} style={{ '--progress': `${amount}%`, '--ring-color': amount < 50 ? '#ff4051' : '#21854e' }}><strong>{percentage(value)}</strong></div><small>{label}</small></div>;
}
export function ObjectiveRow({ objective: o, onOpen }) {
  const photo = /loss|post.harvest|storage/i.test(o.name) ? 'post-harvest' : /yield|flower/i.test(o.name) ? 'flowering' : 'harvest';
  const note = [...o.feedback].sort((a, b) => b.date.localeCompare(a.date))[0];
  return <article className="objective-row"><img className="objective-photo" src={`/pages/objectives/${photo}.png`} alt="" /><div className="objective-row-copy"><small>{o.code} <span>│</span> {o.category}</small><h2>{o.name}</h2><p className="objective-owner"><UserRound size={13} />{o.owner || 'Unassigned'}<span>│</span><CalendarDays size={13} />Deadline {o.end}</p><p>{o.description || o.rationale || 'Define measurable KPIs and link farm activities to this objective.'}</p></div><span className={`objective-health health-${o.health.toLowerCase().replaceAll(' ', '-')}`}>{o.health}</span><div className="objective-row-rings"><ObjectiveRing label="Outcome achievement" value={o.outcome} /><ObjectiveRing label="Execution progress" value={o.execution} /></div><div className="objective-row-counts"><span><BarChart3 size={14} />{o.kpis.filter(k => k.achievement >= 100).length}/{o.kpis.length} KPIs achieved</span><span><FileText size={14} />{o.logs.filter(l => String(l.status).toLowerCase() === 'completed').length}/{o.logs.length} logs completed</span><span className={o.open_blockers ? 'objective-danger' : ''}><CircleAlert size={14} />{o.open_blockers} {o.open_blockers === 1 ? 'blocker' : 'blockers'}</span></div><div className="objective-row-note"><Lightbulb size={16} /><span>{note?.notes || 'No progress update recorded yet.'}</span>{note && <small>{note.date}</small>}</div><Button className="objective-view" onClick={onOpen}>View Details →</Button></article>;
}
export function ObjectiveActivity({ preview, cycle, models, onOpen }) {
  const entries = preview ? previewActivity.map((e, i) => ({ ...e, Icon: [FileText, BarChart3, CircleAlert, FileText, CheckCircle2, MessageSquareText, FileText, CheckCircle2][i] })) : models.flatMap(o => [
    ...o.feedback.map(f => ({ id: `feedback-${f.id}`, date: f.date, title: f.type, description: f.notes, objective: o.id, Icon: MessageSquareText })),
    ...o.evidence.map(e => ({ id: `evidence-${e.id}`, date: e.date, title: 'Evidence uploaded', description: e.name, objective: o.id, Icon: FileText })),
    ...o.logs.map(l => ({ id: `log-${o.id}-${l.id}`, date: l.updated_date || l.activity_date, title: 'Task log synced', description: l.title || l.activity_code || o.name, objective: o.id, Icon: CheckCircle2 })),
  ]).sort((a, b) => String(b.date).localeCompare(String(a.date)));
  return <aside className="objective-activity"><header><h2>Live Activity</h2><span className="objective-live">● Live updates</span></header><div className="objective-activity-list">{entries.slice(0, 8).map(e => <button key={e.id} onClick={() => onOpen(e.objective, 'History')}><span className="objective-activity-icon"><e.Icon size={18} /></span><span><strong>{e.title}</strong><small>{e.description}</small></span><time>{preview ? e.date : String(e.date || '').slice(0, 10)}</time></button>)}{!entries.length && <p className="objective-panel-empty">Activity will appear here as task logs, evidence and progress notes are recorded.</p>}</div><Button variant="ghost" onClick={() => onOpen(models[0]?.id, 'History')} disabled={!models.length}>View All Activity →</Button><span className="sr-only">{cycle.year} objective activity</span></aside>;
}
export function ObjectiveInsights({ preview, models, farmName, blockName, year, onOpen }) {
  const contributions = preview ? previewContributions : models.flatMap(o => o.contributions.map(c => ({ ...c, objective: o.id })));
  const feedback = preview ? previewFeedback : models.flatMap(o => o.feedback.map(f => ({ ...f, objective: o.id }))).sort((a, b) => b.date.localeCompare(a.date));
  const measured = models.flatMap(o => o.kpis.filter(k => k.achievement != null).map(k => ({ ...k, objective: o.id })));
  return <div className="objective-insights"><section><header><Sprout /><div><h2>Farm / Block Contribution</h2><p>Objective progress by farm and block</p></div></header><div className="objective-contributions">{contributions.map(c => <button key={c.id} onClick={() => onOpen(c.objective, 'Analytics')}><span>{c.label || (c.block_id ? blockName(c.block_id) : farmName(c.farm_id))}</span><progress max="100" value={Math.min(100, c.achievement ?? 0)} /><strong>{percentage(c.achievement)}</strong></button>)}{!contributions.length && <p className="objective-panel-empty">Allocate KPI targets to farms and blocks to see their contribution.</p>}</div></section><section><header><BarChart3 /><div><h2>KPI Trend Overview</h2><p>Track key performance indicators over time</p></div><span className="objective-year-tag">{year}</span></header><div className="objective-kpi-overview">{preview ? <PreviewTrend /> : <>{measured.slice(0, 5).map(k => <button key={`${k.objective}-${k.id}`} onClick={() => onOpen(k.objective, 'KPIs')}><span>{k.name}</span><progress max="100" value={Math.min(100, k.achievement)} /><strong>{percentage(k.achievement)}</strong></button>)}<p className="objective-panel-empty">{measured.length ? 'Current verified achievement. Monthly trend history is not recorded yet.' : 'KPI results will appear when linked task logs or verified measurements are available.'}</p></>}</div></section><section><header><MessageSquareText /><div><h2>Recent Feedback & Notes</h2><p>Latest comments, reviews and observations</p></div></header><div className="objective-feedback">{feedback.slice(0, 4).map(f => <button key={f.id} onClick={() => onOpen(f.objective, 'Feedback')}><span className="objective-avatar">{f.author?.split(' ').map(n => n[0]).slice(0, 2).join('')}</span><span><strong>{f.author}</strong><small>{f.notes}</small></span><time>{f.date}</time>{f.sentiment && <span className={`objective-sentiment sentiment-${f.sentiment.toLowerCase().replaceAll(' ', '-')}`}>● {f.sentiment}</span>}</button>)}{!feedback.length && <p className="objective-panel-empty">No feedback recorded yet.</p>}</div><Button variant="ghost" onClick={() => onOpen(feedback[0]?.objective || models[0]?.id, 'Feedback')} disabled={!models.length}>View All Feedback →</Button></section></div>;
}

function PreviewTrend() {
  const series = [
    {name:'Harvest Volume',color:'#087d3a',values:[44,54,55,55,58,68,73,78,81,82,77,83]},
    {name:'Yield per Hectare',color:'#ffb600',values:[30,40,41,42,44,57,62,66,68,62,54,63]},
    {name:'Post-harvest Loss',color:'#ff3449',values:[16,24,28,20,16,15,15,22,21,23,23,21]},
    {name:'Quality Grade A',color:'#9736ff',values:[8,15,17,20,28,34,38,45,49,76,64,73]}
  ];
  const data = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'].map((month,i)=>Object.fromEntries([['month',month],...series.map(s=>[s.name,s.values[i]])]));
  return <div style={{height:185,width:'100%',marginTop:12}}><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{top:8,right:8,left:-22,bottom:0}}><CartesianGrid stroke="#edf0f3"/><XAxis dataKey="month" tick={{fontSize:8}} tickLine={false}/><YAxis domain={[0,100]} ticks={[0,20,40,60,80,100]} tick={{fontSize:8}} tickFormatter={v=>`${v}%`} tickLine={false}/><Tooltip formatter={v=>`${v}%`}/><Legend iconType="circle" iconSize={7} wrapperStyle={{fontSize:8}}/>{series.map(s=><Line key={s.name} type="linear" dataKey={s.name} stroke={s.color} strokeWidth={1.5} dot={{r:2}} />)}</LineChart></ResponsiveContainer></div>;
}
