import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Download, Plus, RefreshCw, Target } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { useAuth } from '@/lib/AuthContext';
import { subscribeToDataChanges } from '@/lib/data-sync';
import { blockLabel, scopeLabel } from '@/lib/farm-scope';
import { ObjectiveRow, ObjectiveActivity, ObjectiveInsights, overviewIcons } from './ObjectiveOverview';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import './objectives.css';
import ObjectiveDetails from './ObjectiveDetails';
import { previewModels, previewSummary } from './objective-preview';

const uid = () => crypto.randomUUID();
const categories = ['Production', 'Financial', 'Sales', 'Operations', 'Quality', 'Farm Management', 'Sustainability', 'Workforce', 'Supply Chain', 'Customer', 'Export', 'Strategic Growth'];
const tabs = ['Overview', 'Sub-Objectives', 'KPIs', 'Tasks', 'Progress', 'Evidence', 'Feedback', 'Blockers', 'Analytics', 'History'];
const fmt = value => value == null ? 'No result' : Number(value).toLocaleString('en-GH', { maximumFractionDigits: 2 });
const pct = value => value == null ? 'No result' : `${Math.round(value)}%`;
const money = value => `GHS ${fmt(value)}`;
const field = (name, label, type = 'text', options, required = false) => ({ name, label, type, options, required });
const clean = cycle => ({ year: cycle.year, revision: cycle.revision || 0, weighted: cycle.weighted || false, objectives: cycle.objectives || [], review: cycle.review || '', close: false });

function Editor({ config, onClose, onSave, busy }) {
  const [values, setValues] = useState(config.initial || {});
  const [error, setError] = useState('');
  const changeSelect = (f, value) => setValues(v => {
    if (f.name === 'farm_id') {
      const option = f.options.find(o => o.value === value);
      return { ...v, farm_id: option?.blockId ? option.farmId : value, block_id: option?.blockId || '' };
    }
    return { ...v, [f.name]: value, ...(f.name === 'block_id' && value ? { farm_id: f.options.find(o => o.value === value)?.farmId || v.farm_id || '' } : {}) };
  });
  return <Dialog open onOpenChange={open => !open && onClose()}><DialogContent className="objective-editor"><DialogHeader><DialogTitle>{config.title}</DialogTitle><DialogDescription>{config.description || 'Save the configuration. Results are calculated from the selected source.'}</DialogDescription></DialogHeader>
    <form onSubmit={async e => { e.preventDefault(); setError(''); try { await onSave(values); } catch (err) { setError(err.message); } }}>
      <div className="objective-form-grid">{config.fields.map(f => <label key={f.name}>{f.label}{f.type === 'select' ? <select required={f.required} value={f.name === 'farm_id' && values.block_id ? `block:${values.block_id}` : values[f.name] ?? ''} onChange={e => changeSelect(f, e.target.value)}><option value="">{f.emptyLabel || 'Select…'}</option>{(f.options || []).filter(o => f.name !== 'block_id' || !values.farm_id || values.farm_id === '__all_farms__' || !o.farmId || o.farmId === values.farm_id).map(o => <option key={o.value ?? o} value={o.value ?? o}>{o.label ?? o}</option>)}</select>
        : f.type === 'textarea' ? <textarea required={f.required} value={values[f.name] ?? ''} onChange={e => setValues(v => ({ ...v, [f.name]: e.target.value }))} />
          : <input type={f.type} required={f.required} step={f.type === 'number' ? 'any' : undefined} value={values[f.name] ?? ''} onChange={e => setValues(v => ({ ...v, [f.name]: f.type === 'number' ? (e.target.value === '' ? null : Number(e.target.value)) : e.target.value }))} />}</label>)}</div>
      {error && <p role="alert" className="objective-error">{error}</p>}<div className="objective-actions"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button disabled={busy}>{busy ? 'Saving…' : 'Save'}</Button></div>
    </form></DialogContent></Dialog>;
}
function Progress({ label, value }) { return <div className="objective-progress"><div><span>{label}</span><strong>{pct(value)}</strong></div><progress aria-label={label} max="100" value={value == null ? 0 : Math.min(100, value)} /></div>; }
function Health({ value }) { return <span className={`objective-health health-${String(value).toLowerCase().replaceAll(' ', '-')}`}>{value}</span>; }
function Table({ headings, children }) { return <div className="objective-table-wrap"><table><thead><tr>{headings.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }

export default function Objectives() {
  const { user } = useAuth();
  const [preview, setPreview] = useState(() => ['localhost', '127.0.0.1'].includes(window.location.hostname));
  const currentYear = Math.max(2026, new Date().getFullYear());
  const [year, setYear] = useState(currentYear), [cycles, setCycles] = useState([]), [farms, setFarms] = useState([]), [blocks, setBlocks] = useState([]);
  const [syncedAt, setSyncedAt] = useState(null);
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [busy, setBusy] = useState(false), [editor, setEditor] = useState(null);
  const [modalId, setModalId] = useState('');
  const [previewEdits, setPreviewEdits] = useState({});
  const [previewRemoved, setPreviewRemoved] = useState([]);
  const [selected, setSelected] = useState(''), [tab, setTab] = useState('Overview'), [screen, setScreen] = useState('Objectives');
  const [search, setSearch] = useState(''), [health, setHealth] = useState(''), [farmFilter, setFarmFilter] = useState(''), [category, setCategory] = useState('');
  const load = useCallback(async () => {
    try { const [c, f, b] = await Promise.all([base44.objectives.list(), base44.entities.Farm.listAll(), base44.entities.FarmBlock.listAll()]); setCycles(c); setFarms(f); setBlocks(b); setSyncedAt(new Date()); setError(''); }
    catch (err) { setError(err.message); } finally { setLoading(false); }
  }, []);
  useEffect(() => { void load(); return subscribeToDataChanges(load, ['ObjectiveCycle', 'DailyActivity', 'Farm', 'FarmBlock'], { refreshOnFocus: true, refreshIntervalMs: 60000 }); }, [load]);
  const cycle = cycles.find(c => c.year === year) || { year, revision: 0, objectives: [], weighted: false, result: { objectives: [], score: null } };
  const result = cycle.result, models = preview ? previewModels.filter(o => !previewRemoved.includes(o.id)).map(o => ({ ...o, ...previewEdits[o.id] })) : result.objectives, detail = models.find(o => o.id === selected);
  const raw = preview ? models.find(o => o.id === selected) : cycle.objectives.find(o => o.id === selected);
  const canManage = !preview && ['super_admin', 'admin'].includes(user?.role), editable = canManage && !cycle.closed_at && year >= currentYear;
  const orderedFarms = [...farms].sort((a, b) => scopeLabel(a.name).localeCompare(scopeLabel(b.name), undefined, { numeric: true, sensitivity: 'base' }));
  const orderedBlocks = blocks.filter(b => blockLabel(b).replace(/^Block\s+/i, '').toUpperCase() !== 'A6').sort((a, b) => String(a.name || a.block_name || a.block_code || '').localeCompare(String(b.name || b.block_name || b.block_code || ''), undefined, { numeric: true, sensitivity: 'base' }));
  const farmOptions = [{ value: '__all_farms__', label: 'A&B' }, ...orderedFarms.map(f => ({ value: f.id, label: scopeLabel(f.name) })), ...orderedBlocks.map(b => ({ value: `block:${b.id}`, label: blockLabel(b).replace(/^Block\s+/i, ''), farmId: b.farm_id, blockId: b.id }))], blockOptions = orderedBlocks.map(b => ({ value: b.id, label: blockLabel(b).replace(/^Block\s+/i, ''), farmId: b.farm_id }));
  const scopeFields = [{ ...field('farm_id', 'Farm / Company', 'select', farmOptions), emptyLabel: 'Admin' }, field('block_id', 'Block (optional)', 'select', blockOptions), field('variety', 'Mango variety')];
  const farmName = id => id === '__all_farms__' ? 'A&B' : scopeLabel(farms.find(f => f.id === id)?.name) || (id ? `Farm ${id}` : 'Admin');
  const blockName = id => blockLabel(blocks.find(b => b.id === id)).replace(/^Block\s+/i, '') || 'Whole farm';
  const save = async next => { setBusy(true); try { await base44.objectives.save(next); await load(); setEditor(null); } finally { setBusy(false); } };
  const updateObjective = next => save({ ...clean(cycle), objectives: cycle.objectives.map(o => o.id === next.id ? next : o) });
  const addRecord = (collection, config) => setEditor({ ...config, save: values => updateObjective({ ...raw, [collection]: [...(raw[collection] || []), { id: uid(), ...values }] }) });
  const openObjective = existing => setEditor({ title: existing ? 'Edit Objective' : 'Create Objective', initial: existing || { id: uid(), code: `OBJ-${year}-${String(cycle.objectives.length + 1).padStart(3, '0')}`, start: `${year}-01-01`, end: `${year}-12-31`, status: 'Active', category: 'Production', priority: 'High', weight: 100, budget: 0, owner: user?.full_name || '', kpis: [], subs: [], allocations: [], feedback: [], blockers: [], evidence: [] },
    fields: [field('name', 'Objective name', 'text', null, true), field('code', 'Objective code', 'text', null, true), field('category', 'Category', 'select', categories, true), field('owner', 'Responsible manager', 'text', null, true), field('department', 'Department'), field('priority', 'Priority', 'select', ['Low', 'Medium', 'High', 'Critical'], true), field('start', 'Start date', 'date', null, true), field('end', 'Deadline', 'date', null, true), ...scopeFields, field('weight', 'Annual weight (%)', 'number', null, true), field('budget', 'Planned budget (GHS)', 'number', null, true), field('status', 'Status', 'select', ['Draft', 'Active', 'Cancelled'], true), field('description', 'Description', 'textarea'), field('rationale', 'Why this objective matters', 'textarea')],
    save: values => save({ ...clean(cycle), objectives: existing ? cycle.objectives.map(o => o.id === existing.id ? values : o) : [...cycle.objectives, values] }) });
  const openKpi = existing => {
    const initial = existing || { id: uid(), target: 100, upper: 0, weight: 100, baseline: 0, direction: 'higher', source: 'task', metric: 'completion', unit: '%', frequency: 'Monthly', manual_actual: null };
    setEditor({ title: existing ? 'Edit KPI / verified result' : 'Add KPI', initial, description: 'Automatic uses all eligible task logs in scope; Task uses explicitly linked logs. Hybrid adds a documented adjustment. Yield supports kg or tonnes; other derived ratios require a verified manual result.',
      fields: [field('name', 'KPI name', 'text', null, true), field('sub_id', 'Sub-objective (optional)', 'select', raw.subs.map(s => ({ value: s.id, label: s.name }))), field('unit', 'Unit', 'text', null, true), field('baseline', 'Baseline', 'number'), field('target', 'Target / range minimum', 'number', null, true), field('upper', 'Range maximum', 'number'), field('weight', 'KPI weight', 'number', null, true), field('direction', 'Direction', 'select', [{ value: 'higher', label: 'Higher is better' }, { value: 'lower', label: 'Lower is better' }, { value: 'range', label: 'Target range' }], true), field('source', 'Data source', 'select', ['automatic', 'task', 'manual', 'hybrid'], true), field('metric', 'Task Log measurement', 'select', ['yield', 'cost', 'revenue', 'count', 'completion'], true), field('frequency', 'Measurement frequency', 'select', ['Daily', 'Weekly', 'Monthly', 'Quarterly', 'Seasonal', 'Annual']), field('owner', 'Responsible person'), field('manual_actual', 'Verified actual / hybrid adjustment', 'number'), field('reason', 'Source, evidence reference and reason', 'textarea'), field('description', 'Description', 'textarea')],
      save: values => updateObjective({ ...raw, kpis: existing ? raw.kpis.map(k => k.id === existing.id ? values : k) : [...raw.kpis, values] }) });
  };
  const filtered = useMemo(() => models.filter(o => (!health || o.health === health) && (!farmFilter || (farmFilter === '__admin__' ? !o.farm_id && !o.block_id : farmFilter === '__all_farms__' ? Boolean(o.farm_id || o.block_id || o.logs.some(l => l.farm_id || l.block_id)) : farmFilter.startsWith('block:') ? o.block_id === farmFilter.slice(6) || o.logs.some(l => l.block_id === farmFilter.slice(6)) : o.farm_id === farmFilter || o.logs.some(l => l.farm_id === farmFilter))) && (!category || o.category === category) && JSON.stringify([o.name, o.code, o.owner, o.department, o.variety, o.kpis, o.feedback, o.blockers, o.logs, farmName(o.farm_id), blockName(o.block_id)]).toLowerCase().includes(search.toLowerCase())), [models, health, farmFilter, category, search, farms, blocks]);
  const exportCsv = () => {
    const rows = [['Year', 'Code', 'Objective', 'Owner', 'Health', 'Execution %', 'Outcome %', 'Budget GHS', 'Cost GHS', 'Revenue GHS'], ...filtered.map(o => [year, o.code, o.name, o.owner, o.health, o.execution, o.outcome, o.budget, o.cost, o.revenue])];
    const csv = rows.map(row => row.map(v => `"${String(v ?? '').replace(/^[=+@-]/, "'$&").replaceAll('"', '""')}"`).join(',')).join('\r\n');
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })), a = document.createElement('a'); a.href = url; a.download = `objectives-${year}.csv`; a.click(); URL.revokeObjectURL(url);
  };
  const openYear = () => setEditor({ title: 'Create New Year Objectives', description: 'Copy the structure and targets with fresh identifiers. Actuals, evidence, feedback, blockers and task links are reset.', initial: { next_year: Math.max(currentYear + 1, year + 1), copy: 'yes' }, fields: [field('next_year', 'New year', 'number', null, true), field('copy', 'Copy selected year structure', 'select', ['yes', 'no'])], save: values => {
    const nextYear = values.next_year;
    if (!Number.isInteger(nextYear) || nextYear < currentYear || cycles.some(c => c.year === nextYear)) throw new Error('Choose a new current or future year.');
    const objectives = values.copy === 'yes' ? cycle.objectives.map((o, i) => {
      const subs = new Map(o.subs.map(s => [s.id, uid()])), kpis = new Map(o.kpis.map(k => [k.id, uid()]));
      return { ...o, id: uid(), code: `OBJ-${nextYear}-${String(i + 1).padStart(3, '0')}`, status: 'Draft', start: `${nextYear}-01-01`, end: `${nextYear}-12-31`, subs: o.subs.map(s => ({ ...s, id: subs.get(s.id) })), kpis: o.kpis.map(k => ({ ...k, id: kpis.get(k.id), sub_id: subs.get(k.sub_id) || '', manual_actual: null, reason: '', evidence: [] })), allocations: o.allocations.map(a => ({ ...a, id: uid(), kpi_id: kpis.get(a.kpi_id) })), feedback: [], blockers: [], evidence: [] };
    }) : [];
    return save({ year: nextYear, revision: 0, weighted: cycle.weighted, objectives, review: '', close: false }).then(() => { setYear(nextYear); setSelected(''); });
  } });
  const openClose = () => setEditor({ title: `Close ${year} Objective Year`, description: `Review ${models.length} objectives: ${models.filter(o => o.health === 'Completed').length} achieved. Annual score ${pct(result.score)}. Closing permanently freezes the calculated KPIs and contributing logs.`, initial: { review: cycle.review || '' }, fields: [field('review', 'Final outcomes, lessons learned and next-year recommendations', 'textarea', null, true)], save: values => save({ ...clean(cycle), review: values.review, close: true }) });
  const addFeedback = () => addRecord('feedback', { title: 'Add Progress & Feedback', initial: { date: new Date().toISOString().slice(0, 10), author: user.full_name, type: 'Progress Update' }, fields: [field('date', 'Date', 'date', null, true), field('author', 'Author', 'text', null, true), field('type', 'Type', 'select', ['General Update', 'Progress Update', 'Observation', 'Problem', 'Blocker', 'Recommendation', 'Corrective Action', 'Management Decision', 'Lesson Learned'], true), field('notes', 'Notes', 'textarea', null, true), field('kpi_id', 'KPI affected', 'select', raw.kpis.map(k => ({ value: k.id, label: k.name }))), ...scopeFields] });
  const blockerFields = [field('name', 'Blocker', 'text', null, true), field('description', 'Description', 'textarea'), field('severity', 'Severity', 'select', ['Low', 'Medium', 'High', 'Critical'], true), field('owner', 'Responsible person', 'text', null, true), field('due', 'Expected resolution', 'date'), field('status', 'Status', 'select', ['Open', 'Under Investigation', 'In Progress', 'Resolved', 'Accepted Risk'], true), field('action', 'Corrective action', 'textarea'), field('resolution', 'Resolution / accepted-risk reason', 'textarea'), ...scopeFields];
  const summary = preview ? previewSummary : [['Overall achievement', pct(result.score)], ['On Track', models.filter(o => o.health === 'On Track').length], ['At Risk', models.filter(o => ['At Risk', 'Attention Needed'].includes(o.health)).length], ['Behind', models.filter(o => o.health === 'Behind').length], ['Completed', models.filter(o => o.health === 'Completed').length], ['Open blockers', models.reduce((s, o) => s + o.open_blockers, 0)]];
  return <div className="objectives-page" data-preserve-colors="true"><header className="objective-hero"><Target size={42} /><div><h1>Objectives</h1><p>Align annual strategy with farm activity, measurable outcomes and evidence.</p></div></header>
    <div className="objective-toolbar">{['localhost', '127.0.0.1'].includes(window.location.hostname) && <button className="objective-preview-toggle" onClick={() => { setPreview(!preview); setSelected(''); }}>{preview ? 'Dummy data · Show saved data' : 'Show reference dummy data'}</button>}<label>Year <select aria-label="Objective year" value={year} onChange={e => { setYear(Number(e.target.value)); setSelected(''); }}>{[...new Set([...Array.from({ length: currentYear - 2026 + 6 }, (_, i) => 2026 + i), ...cycles.map(c => c.year)])].sort((a, b) => a - b).map(y => <option key={y}>{y}</option>)}</select></label><Health value={cycle.closed_at ? 'Closed' : year < currentYear ? 'Historical' : 'Active cycle'} /><span className="objective-live">● Live sync</span><small className="objective-sync-time">{syncedAt ? `Last synced ${syncedAt.toLocaleTimeString('en-GH', { hour: '2-digit', minute: '2-digit' })}` : 'Connecting…'}</small><div className="objective-actions"><Button variant="outline" onClick={load} disabled={busy}><RefreshCw size={16} /> Refresh</Button><Button variant="outline" onClick={exportCsv}><Download size={16} /> Export CSV</Button>{(canManage || preview) && <Button variant="outline" onClick={preview ? () => setPreview(false) : openYear} disabled={busy}>Create New Year</Button>}{(editable || preview) && <Button onClick={() => { if (preview) setPreview(false); else openObjective(); }} disabled={busy}><Plus size={16} /> Create Objective</Button>}</div></div>
    {error && <p role="alert" className="objective-error">{error}</p>}{loading ? <p role="status">Loading objectives and operational results…</p> : <>
      {cycle.closed_at && <p className="objective-notice">Closed on {new Date(cycle.closed_at).toLocaleDateString('en-GH')}. Results and contributing records are preserved in a historical snapshot.</p>}
      <div className="objective-summary">{summary.map(([label, value, delta], i) => { const Icon = overviewIcons[i]; return <div key={label} className={`objective-stat objective-stat-${i}`}><span className="objective-stat-icon"><Icon size={23} /></span><div><span>{label}</span><strong>{value}</strong>{delta && <b className={`objective-stat-delta ${i === 2 ? 'objective-danger' : ''}`}>{delta.startsWith('-') ? '▼' : '▲'} {delta}</b>}{preview && <svg className="objective-sparkline" viewBox="0 0 60 28" aria-hidden="true"><polyline points={i === 3 ? '1,17 10,18 20,9 30,19 41,16 51,21 59,19' : '1,22 10,16 20,19 31,7 41,14 51,9 59,4'} fill="none" stroke="currentColor" strokeWidth="1.5" /></svg>}<small>{preview ? 'vs. last month' : i === 0 ? 'Verified annual results' : 'Current annual cycle'}</small></div></div>; })}</div>
      {detail ? <section className="objective-workspace"><div className="objective-toolbar"><Button variant="outline" onClick={() => setSelected('')}><ArrowLeft size={16} /> All objectives</Button><div><small>{detail.code}</small><h2>{detail.name}</h2></div><Health value={detail.health} />{editable && <Button variant="outline" onClick={() => openObjective(raw)}>Edit Objective</Button>}</div>
        <div className="objective-tabs" role="tablist" aria-label="Objective detail">{tabs.map(t => <button key={t} role="tab" aria-selected={tab === t} onClick={() => setTab(t)}>{t}</button>)}</div><div role="tabpanel" aria-label={tab} className="objective-panel">
          {tab === 'Overview' && <><p>{detail.description || detail.rationale || 'No description added.'}</p><div className="objective-detail-grid"><div><Progress label="Execution progress" value={detail.execution} /><Progress label="Outcome achievement" value={detail.outcome} /><Progress label="Expected progress by date" value={detail.expected} /></div><dl><dt>Responsible manager</dt><dd>{detail.owner}</dd><dt>Scope</dt><dd>{farmName(detail.farm_id)} / {blockName(detail.block_id)} {detail.variety}</dd><dt>Period</dt><dd>{detail.start} → {detail.end}</dd><dt>Priority / department</dt><dd>{detail.priority} / {detail.department || 'Unassigned'}</dd></dl></div><div className="objective-finance">{[['Planned budget', detail.budget], ['Actual task cost', detail.cost], ['Budget variance', detail.budget_variance], ['Recorded task revenue', detail.revenue]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{money(value)}</strong></div>)}</div><p className="objective-muted">Activity completion and business outcome are measured separately. Missing KPI results remain “No result”. Cost and revenue cover linked Daily Task Logs only.</p></>}
          {tab === 'Sub-Objectives' && <>{editable && <Button onClick={() => addRecord('subs', { title: 'Add Sub-Objective', initial: { weight: 100 }, fields: [field('name', 'Name', 'text', null, true), field('owner', 'Owner'), field('weight', 'Weight', 'number', null, true), field('description', 'Description', 'textarea'), ...scopeFields] })}>Add Sub-Objective</Button>}<div className="objective-grid">{detail.subs.map(s => <article key={s.id}><h3>{s.name}</h3><p>{s.description}</p><p>{s.owner} · Weight {s.weight}</p><Progress label="KPI achievement" value={s.achievement} /></article>)}</div>{!detail.subs.length && <p>No sub-objectives configured.</p>}</>}
          {tab === 'KPIs' && <>{editable && <Button onClick={() => openKpi()}>Add KPI</Button>}<Table headings={['KPI / source', 'Direction', 'Baseline', 'Target', 'Actual', 'Variance', 'Achievement', 'Weight', 'Action']}>{detail.kpis.map(k => <tr key={k.id}><td><strong>{k.name}</strong><small>{k.source} · {k.frequency} · {k.unit}</small></td><td>{k.direction}</td><td>{fmt(k.baseline)}</td><td>{fmt(k.target)}{k.direction === 'range' && `–${fmt(k.upper)}`}</td><td>{fmt(k.actual)}</td><td>{fmt(k.variance)}</td><td>{pct(k.achievement)}</td><td>{k.weight}</td><td>{editable && <Button variant="outline" onClick={() => openKpi(raw.kpis.find(v => v.id === k.id))}>Edit / result</Button>}</td></tr>)}</Table>{!detail.kpis.length && <p>Add measurable KPIs to calculate outcome achievement.</p>}</>}
          {tab === 'Tasks' && <><p>Existing Daily Task Logs linked to this objective. Open the Task Log to edit a source record.</p><Link to="/admin/farm-daily-activities/activities/records">Open Daily Task Log →</Link><Table headings={['Date', 'Task / staff', 'Farm / block', 'Status', 'Cost', 'Output (kg)']}>{detail.logs.map(l => <tr key={l.id}><td>{l.activity_date}</td><td><Link to={`/admin/farm-daily-activities/activities/records?activityId=${encodeURIComponent(l.id)}`}>{l.title || l.activity_code || l.id}</Link><small>{l.responsible || l.supervisor_name}</small></td><td>{l.farm_name || farmName(l.farm_id)} / {l.block_name || blockName(l.block_id)}</td><td>{l.status}</td><td>{money(l.actual_cost ?? l.cost)}</td><td>{fmt(l.output_quantity_kg)}</td></tr>)}</Table>{!detail.logs.length && <p>No linked task logs. Select this objective and KPI when recording daily work.</p>}</>}
          {['Progress', 'Feedback'].includes(tab) && <>{editable && <Button onClick={addFeedback}>Add Progress & Feedback</Button>}<div className="objective-timeline">{[...detail.feedback].sort((a, b) => b.date.localeCompare(a.date)).map(f => <article key={f.id}><small>{f.date} · {f.author}</small><h3>{f.type}</h3><p>{f.notes}</p></article>)}</div>{!detail.feedback.length && <p>No progress notes recorded.</p>}</>}
          {tab === 'Evidence' && <><p>Use the existing private file service for images, video, PDF, DOCX and text files up to 5 MB.</p>{editable && <label className="objective-upload">Upload evidence<input type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain" disabled={busy} onChange={async e => { const file = e.target.files?.[0]; if (!file) return; setBusy(true); try { const uploaded = await base44.files.upload(file, cycle.id); await updateObjective({ ...raw, evidence: [...raw.evidence, { id: uploaded.id, name: uploaded.name, url: uploaded.url, date: new Date().toISOString(), author: user.full_name, description: '' }] }); } catch (err) { setError(err.message); } finally { setBusy(false); e.target.value = ''; } }} /></label>}<Table headings={['File', 'Date', 'Uploader', 'Preview / download']}>{detail.evidence.map(e => <tr key={e.id}><td>{e.name}</td><td>{e.date.slice(0, 10)}</td><td>{e.author}</td><td><a href={`${e.url}?preview=1`} target="_blank" rel="noreferrer">Preview</a> · <a href={e.url}>Download</a></td></tr>)}</Table>{!detail.evidence.length && <p>No objective evidence uploaded.</p>}</>}
          {tab === 'Blockers' && <>{editable && <Button onClick={() => addRecord('blockers', { title: 'Record Blocker', initial: { severity: 'Medium', status: 'Open', owner: user.full_name, action: '' }, fields: blockerFields })}>Record Blocker</Button>}<div className="objective-grid">{detail.blockers.map(b => <article key={b.id}><Health value={b.status} /><h3>{b.name}</h3><p>{b.description}</p><p>{b.severity} · {b.owner} · Due {b.due || 'Unspecified'}</p><p>Corrective action: {b.action || 'Not recorded'}</p><p>Resolution: {b.resolution || 'Pending'}</p>{editable && <Button variant="outline" onClick={() => setEditor({ title: 'Update Blocker', initial: raw.blockers.find(v => v.id === b.id), fields: blockerFields, save: values => updateObjective({ ...raw, blockers: raw.blockers.map(v => v.id === b.id ? values : v) }) })}>Update / resolve</Button>}</article>)}</div>{!detail.blockers.length && <p>No blockers recorded.</p>}</>}
          {tab === 'Analytics' && <><h3>Farm / Block Contribution</h3>{editable && <Button variant="outline" onClick={() => addRecord('allocations', { title: 'Allocate Farm / Block Target', fields: [field('kpi_id', 'KPI', 'select', raw.kpis.map(k => ({ value: k.id, label: k.name })), true), field('farm_id', 'Farm / Block', 'select', farmOptions, true), field('block_id', 'Block', 'select', blockOptions), field('target', 'Allocated target', 'number', null, true)] })}>Allocate target</Button>}<Table headings={['Farm', 'Block', 'Target', 'Actual', 'Achievement', 'Sources']}>{detail.contributions.map(a => <tr key={a.id}><td>{farmName(a.farm_id)}</td><td>{blockName(a.block_id)}</td><td>{fmt(a.target)} {a.unit}</td><td>{fmt(a.actual)}</td><td>{pct(a.achievement)}</td><td><Button variant="outline" onClick={() => setTab('Tasks')}>{a.source_ids.length} logs</Button></td></tr>)}</Table><h3>Analyse Performance</h3><ul>{detail.kpis.filter(k => k.achievement !== null && k.achievement < 100).map(k => <li key={k.id}>Recorded fact: {k.name} achievement {pct(k.achievement)}; variance {fmt(k.variance)} {k.unit}.</li>)}<li>Recorded fact: {detail.open_blockers} open blockers; {detail.critical_blockers} critical; {detail.overdue} overdue linked tasks.</li>{detail.budget_variance > 0 && <li>Recorded fact: task costs exceed planned budget by {money(detail.budget_variance)}.</li>}</ul><p className="objective-notice">Management attention: review deficient KPIs and unresolved blockers. These records show associations; they do not prove causes.</p></>}
          {tab === 'History' && <><p>Server audit trail for this annual cycle; source records are also audited by the existing Task Log API.</p><div className="objective-timeline">{[...(cycle.history || [])].reverse().map((h, i) => <article key={`${h.date}-${i}`}><small>{h.date} · {h.author}</small><p>{h.action}</p></article>)}</div></>}
        </div></section> : <><div className="objective-tabs">{['Objectives', 'Annual Review', 'Year Comparison'].map(s => <button key={s} aria-pressed={screen === s} onClick={() => setScreen(s)}>{s === 'Objectives' ? `Objectives (${preview ? 8 : models.length})` : s}</button>)}</div>
          {screen === 'Objectives' && <><div className="objective-overview-layout"><div className="objective-overview-main"><div className="objective-filters"><input aria-label="Search objectives" placeholder="Search objectives, KPIs, tasks, staff, feedback…" value={search} onChange={e => setSearch(e.target.value)} /><select aria-label="Health filter" value={health} onChange={e => setHealth(e.target.value)}><option value="">All health statuses</option>{['On Track', 'Attention Needed', 'At Risk', 'Behind', 'Completed', 'No result', 'Draft', 'Cancelled'].map(h => <option key={h}>{h}</option>)}</select><select aria-label="Farm filter" value={farmFilter} onChange={e => setFarmFilter(e.target.value)}><option value="">Admin & all farms</option><option value="__admin__">Admin</option>{farmOptions.map(f => <option key={f.value} value={f.value}>{f.label}</option>)}</select><select aria-label="Category filter" value={category} onChange={e => setCategory(e.target.value)}><option value="">All categories</option>{categories.map(c => <option key={c}>{c}</option>)}</select></div><div className="objective-list">{filtered.map(o => <ObjectiveRow key={o.id} objective={o} onOpen={() => setModalId(o.id)} />)}</div>{!filtered.length && <div className="objective-empty"><Target size={36} /><h2>{models.length ? 'No objectives match these filters' : `Plan your ${year} objectives`}</h2><p>Create an objective, define its KPIs, then link daily farm activity to measurable results.</p>{editable && <Button onClick={() => openObjective()}>Create Objective</Button>}</div>}</div><ObjectiveActivity preview={preview} cycle={cycle} models={models} onOpen={(id, nextTab) => { if (id) { setSelected(id); setTab(nextTab); } }} /></div><ObjectiveInsights preview={preview} models={models} farmName={farmName} blockName={blockName} year={year} onOpen={(id, nextTab) => { if (id) { setSelected(id); setTab(nextTab); } }} /></>}
          {screen === 'Annual Review' && <section className="objective-panel"><h2>{year} Annual Review</h2><p>Achievement: {pct(result.score)} · {cycle.weighted ? 'Weighted annual scoring' : 'Equal objective weighting'}</p><p>Objective weights total {cycle.objectives.filter(o => o.status !== 'Cancelled').reduce((s, o) => s + o.weight, 0)}%.</p>{editable && <Button variant="outline" disabled={busy} onClick={() => save({ ...clean(cycle), weighted: !cycle.weighted }).catch(err => setError(err.message))}>{cycle.weighted ? 'Use equal weighting' : 'Enable weighted annual score (100%)'}</Button>}<Table headings={['Objective', 'Outcome', 'Execution', 'Budget', 'Actual Cost', 'Blockers']}>{models.map(o => <tr key={o.id}><td>{o.name}</td><td>{pct(o.outcome)}</td><td>{pct(o.execution)}</td><td>{money(o.budget)}</td><td>{money(o.cost)}</td><td>{o.open_blockers}</td></tr>)}</Table><p>{cycle.review || 'Management notes and lessons learned have not been recorded.'}</p>{canManage && !cycle.closed_at && year <= currentYear && <Button disabled={busy || !models.length} onClick={openClose}>Review & Close Objective Year</Button>}</section>}
          {screen === 'Year Comparison' && <section className="objective-panel"><h2>Historical Performance</h2><Table headings={['Year', 'Achievement', 'Objectives', 'Task Cost', 'Task Revenue', 'Cycle']}>{[...cycles].sort((a, b) => a.year - b.year).map(c => <tr key={c.id}><td><button onClick={() => { setYear(c.year); setScreen('Annual Review'); }}>{c.year}</button></td><td>{pct(c.result.score)}</td><td>{c.objectives.length}</td><td>{money(c.result.objectives.reduce((s, o) => s + o.cost, 0))}</td><td>{money(c.result.objectives.reduce((s, o) => s + o.revenue, 0))}</td><td>{c.closed_at ? 'Frozen snapshot' : 'Live results'}</td></tr>)}</Table><p className="objective-muted">Financial totals can overlap where logs support multiple objectives. Compare individual objectives before interpreting company totals.</p></section>}
        </>}
    </>}<img className="objective-landscape-footer" src="/pages/objectives/footer.png" alt="Sustainable orchards, thriving communities. Better farms today, stronger communities tomorrow, a greener Ghana always." />{models.find(o => o.id === modalId) && <ObjectiveDetails objective={models.find(o => o.id === modalId)} preview={preview} onDelete={() => { setPreviewRemoved(ids => [...ids, modalId]); setModalId(''); }} onClose={() => setModalId('')} onManage={nextTab => { setSelected(modalId); setTab(nextTab); setModalId(''); }} onUpdate={() => { const existing = models.find(o => o.id === modalId); setModalId(''); if (preview) setEditor({ title: 'Update Preview Objective', initial: existing, fields: [field('name', 'Objective name', 'text', null, true), field('owner', 'Responsible manager'), field('end', 'Deadline', 'date'), field('description', 'Description', 'textarea')], save: async values => { setPreviewEdits(edits => ({ ...edits, [existing.id]: values })); setEditor(null); } }); else if (existing) openObjective(cycle.objectives.find(o => o.id === existing.id)); }} />}{editor && <Editor key={editor.title + (editor.initial?.id || '')} config={editor} busy={busy} onClose={() => setEditor(null)} onSave={editor.save} />}
  </div>;
}
