import { useCallback, useEffect, useRef, useState } from 'react';
import { Box, Users, CircleCheck, TriangleAlert, Wrench, CircleX, Clock, FileText, User, ChartNoAxesColumnIncreasing, Search, Plus, ArrowRight, MoreHorizontal } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { subscribeToDataChanges } from '@/lib/data-sync';
import { blockLabel, scopeLabel } from '@/lib/farm-scope';
import InventoryItemDialog from '@/components/farm/InventoryItemDialog';
import './tools-equipment.css';
const categories = ['Tool','Equipment','Material'];
const statuses = ['In Use','Available','Finished','Under Repair','Damaged'];
const money = (v) => v === '' || v == null ? '—' : `GH₵${Number(v).toLocaleString('en-GH')}`;
const tone = (s) => ({'In Use':'green',Available:'blue',Finished:'slate','Under Repair':'orange',Damaged:'red',Completed:'green','In Progress':'gold'}[s] || 'slate');
function Badge({value}) { return <span className={`te-badge te-${tone(value)}`}>{value}</span>; }
function Panel({title,icon:Icon,children,onView,id}) { return <section className="te-panel" id={id}><header><h2><Icon/>{title}</h2>{onView && <button onClick={onView}>View All <ArrowRight/></button>}</header>{children}</section>; }
function Table({headers,children}) { return <div className="te-table"><table><thead><tr>{headers.map((h)=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
export default function ToolsEquipment() {
 const preview = import.meta.env.DEV;
 const [items,setItems]=useState([]), [events,setEvents]=useState([]), [query,setQuery]=useState(''), [category,setCategory]=useState(''), [status,setStatus]=useState(''), [scope,setScope]=useState(''), [error,setError]=useState(''), [loading,setLoading]=useState(true), [dialog,setDialog]=useState(null), [saving,setSaving]=useState(false), [expanded,setExpanded]=useState('');
 const register=useRef(null);
 const [farms,setFarms]=useState([]), [blocks,setBlocks]=useState([]);
 const loadScope=useCallback(async()=>{try{const [nextFarms,nextBlocks]=await Promise.all([base44.entities.Farm.listAll(),base44.entities.FarmBlock.listAll()]);setFarms(nextFarms);setBlocks(nextBlocks);}catch{setError('Unable to load farms and blocks. Please retry.');}},[]);
 useEffect(()=>{void loadScope();return subscribeToDataChanges(loadScope,['Farm','FarmBlock'],{refreshOnFocus:true,refreshIntervalMs:60000});},[loadScope]);
 const load=useCallback(async()=>{try { if(preview){const {toolsPreview,toolsEvents}=await import('./tools-preview');setItems(JSON.parse(localStorage.getItem('jba:tools-preview:v1') || 'null') || toolsPreview);setEvents(toolsEvents);}else{setItems(await base44.entities.Equipment.listAll('-created_date'));}setError('');}catch{setError('Unable to load inventory. Please retry.');}finally{setLoading(false);}},[preview]);
 useEffect(()=>{void load();return preview ? undefined : subscribeToDataChanges(load,['Equipment','EquipmentUsage'],{refreshOnFocus:true});},[load,preview]);
 const compareLabels=(a,b)=>a.label.localeCompare(b.label,undefined,{numeric:true,sensitivity:'base'});
 const scopeFarms=farms.map(f=>({value:`farm:${f.id}`,label:scopeLabel(f.name||f.farm_name||f.farm_code),record:f})).sort(compareLabels);
 const scopeBlocks=blocks.map(b=>({value:`block:${b.id}`,label:blockLabel(b),record:b})).sort(compareLabels);
 const selectedFarm=scopeFarms.find(f=>f.value===scope)?.record;
 const selectedBlock=scopeBlocks.find(b=>b.value===scope)?.record;
 const blockFarm=farms.find(f=>String(f.id)===String(selectedBlock?.farm_id));
 const matchesFarm=(r,f)=>String(r.farm_id||r.farm_assigned)===String(f.id)||scopeLabel(r.farm_assigned)===scopeLabel(f.name||f.farm_name||f.farm_code);
 const matchesScope=r=>!scope||(selectedFarm?matchesFarm(r,selectedFarm):selectedBlock?(String(r.block_id)===String(selectedBlock.id)||(blockLabel(r.current_location)===blockLabel(selectedBlock)&&(!blockFarm||matchesFarm(r,blockFarm)))):false);
 const rows=items.filter(r=>(!query || [r.equipment_code,r.equipment_name,r.assigned_operator].join(' ').toLowerCase().includes(query.toLowerCase()))&&(!category||r.category===category)&&(!status||r.status===status)&&matchesScope(r));
 const filtered=Boolean(query||category||status||scope);
 const metrics=[['Total Items',Box,'green',128,()=>true],['In Use',Users,'green',34,r=>r.status==='In Use'],['Available',CircleCheck,'blue',52,r=>r.status==='Available'],['Low Stock / Finished',TriangleAlert,'gold',9,r=>r.status==='Finished'],['Under Repair',Wrench,'orange',6,r=>r.status==='Under Repair'],['Broken / Damaged',CircleX,'red',4,r=>r.status==='Damaged']];
 const view=(section)=>{setExpanded(expanded===section?'':section);};
 const save=async(values)=>{setSaving(true);try{const id=dialog?.id; if(preview){const next=id?items.map(r=>r.id===id?{...r,...values}:r):[{...values,id:crypto.randomUUID()},...items];localStorage.setItem('jba:tools-preview:v1',JSON.stringify(next));setItems(next);}else{if(id)await base44.entities.Equipment.update(id,values);else await base44.entities.Equipment.create(values);await load();}setDialog(null);}finally{setSaving(false);}};
 const repairs=rows.filter(r=>r.last_maintenance_date);
 const usage=rows.filter(r=>r.status==='In Use'||r.status==='Available'||(preview&&r.equipment_code==='EQ-2024-014'));
 const select=(label,value,set,options)=><select aria-label={label} value={value} onChange={e=>set(e.target.value)}><option value="">{label}</option>{options.map(v=><option key={v}>{v}</option>)}</select>;
 return <div className="tools-equipment" data-preserve-colors="true">
 <div className="te-filters"><label className="te-search"><Search/><input aria-label="Search inventory" placeholder="Search items, ID numbers, staff..." value={query} onChange={e=>setQuery(e.target.value)}/></label>{select('All Categories',category,setCategory,categories)}{select('All Statuses',status,setStatus,statuses)}<select aria-label="Farm / Block filter" value={scope} onChange={e=>setScope(e.target.value)}><option value="">A&amp;B</option>{[...scopeFarms,...scopeBlocks].map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select><button className="te-add" onClick={()=>setDialog({})}><Plus/>Add New Item</button></div>
 {error&&<div role="alert">{error} <button onClick={()=>{void load();void loadScope();}}>Retry</button></div>}{loading&&<p role="status">Loading inventory…</p>}
 <div className="te-metrics">{metrics.map(([label,Icon,color,total,predicate])=><section key={label}><span className={`te-icon te-${color}`}><Icon/></span><div><h2>{label}</h2><strong>{preview&&!filtered&&items.length===7?total:rows.filter(predicate).length}</strong></div></section>)}</div>
 <div className="te-middle"><Panel title="Current Usage & Assignment" icon={Users} onView={()=>view('usage')}><Table headers={['ID No.','Item','Type','Used By','Farm/Block','Status']}>{usage.slice(0,expanded==='usage'?undefined:5).map(r=><tr key={r.id}><td>{r.equipment_code}</td><td>{r.equipment_name}</td><td>{r.category}</td><td>{r.status==='Available'?'Not Assigned':r.assigned_operator||'Not Assigned'}</td><td>{r.farm_assigned} / {r.current_location}</td><td><Badge value={preview&&r.equipment_code==='EQ-2024-014'?'In Use':r.status}/></td></tr>)}</Table></Panel>
 <Panel title="Recent Activity Timeline" icon={Clock} onView={()=>view('timeline')}><div className="te-timeline">{(preview?[...rows.filter(r=>r.created_date).map(r=>[String(r.created_date).slice(0,10),tone(r.status),`${r.equipment_name} � ${r.record_status === 'Draft' ? 'Draft saved' : r.status}`,`${r.farm_assigned||'Unassigned'} � ${r.assigned_operator||'Not assigned'}`]),...events]:rows.filter(r=>r.updated_date||r.created_date).map(r=>[String(r.updated_date||r.created_date).slice(0,10),tone(r.status),`${r.equipment_name} · ${r.status}`,`${r.farm_assigned||'Unassigned'} · ${r.assigned_operator||'Not assigned'}`])).slice(0,expanded==='timeline'?undefined:5).map(([time,color,title,detail],i)=>{const Icon=[FileText,Wrench,User,Box,CircleX][i%5];return <div className="te-event" key={title}><time>{time}</time><i className={`te-dot te-${color}`}/><span className={`te-event-icon te-${color}`}><Icon/></span><div><strong>{title}</strong><p>{detail}</p></div></div>;})}{!preview&&!rows.length&&<p className="te-empty">No recent activity.</p>}</div></Panel></div>
 <div ref={register}><Panel title="Inventory Register" icon={Box} onView={()=>view('inventory')}><Table headers={['ID Number','Item Name','Category','Purchase Date','Purchase Cost (GH₵)','Current Status','Used By / Assigned To','Farm','Block','Remaining Qty / Unit','Last Repair Date','Repair Cost (GH₵)','Actions']}>{rows.map(r=><tr key={r.id}><td>{r.equipment_code||'—'}</td><td>{r.equipment_name}</td><td>{r.category}</td><td>{r.purchase_date||'—'}</td><td>{money(r.purchase_cost)}</td><td><Badge value={r.status}/></td><td>{r.assigned_operator||'Not Assigned'}</td><td>{r.farm_assigned||'—'}</td><td>{r.current_location||'—'}</td><td>{r.remaining_quantity||'—'}</td><td>{r.last_maintenance_date||'—'}</td><td>{money(r.repair_cost)}</td><td><button className="te-more" aria-label={`Edit ${r.equipment_name}`} onClick={()=>setDialog(r)}><MoreHorizontal/></button></td></tr>)}{!rows.length&&<tr><td colSpan={13} className="te-empty">No inventory items match your filters.</td></tr>}</Table></Panel></div>
 <div className="te-bottom"><Panel title="Repairs & Maintenance Log" icon={Wrench} onView={()=>view('repairs')}><Table headers={['Item ID','Item','Issue','Repair Status','Repair Date','Repair Cost (GH₵)','Repaired By']}>{repairs.slice(0,expanded==='repairs'?undefined:3).map((r,i)=><tr key={r.id}><td>{r.equipment_code}</td><td>{r.equipment_name}</td><td>{r.repair_issue||(preview?['Nozzle damage','Motor servicing','Starting fault'][i]:'—')}</td><td><Badge value={r.status==='Under Repair'?'In Progress':'Completed'}/></td><td>{r.last_maintenance_date}</td><td>{money(r.repair_cost)}</td><td>{r.repaired_by||(preview?['K. Owusu','AquaFix Ltd.','Bright Mechanics'][i]:'—')}</td></tr>)}</Table></Panel>
 <Panel title="Stock & Category Overview" icon={ChartNoAxesColumnIncreasing}><div className="te-overview"><div><h3>Items by Category</h3>{categories.map((c,i)=>{const count=preview&&!filtered&&items.length===7?[42,18,68][i]:rows.filter(r=>r.category===c).length;const Icon=[Wrench,ChartNoAxesColumnIncreasing,Box][i];return <div className="te-bar" key={c}><Icon/><span>{c==='Tool'?'Tools':c==='Material'?'Materials':c}</span><div><i className={`te-${['green','blue','gold'][i]}`} style={{width:`${count/Math.max(preview&&!filtered?70:rows.length,1)*100}%`}}/></div><b>{count}</b></div>;})}</div><div><h3>Status Breakdown</h3>{['Available','In Use','Under Repair','Finished','Broken / Damaged'].map((s,i)=>{const count=preview&&!filtered&&items.length===7?[52,34,6,9,4][i]:rows.filter(r=>r.status===(i===4?'Damaged':s)).length;return <div className="te-bar te-status-bar" key={s}><span>{s}</span><div><i className={`te-${['blue','green','orange','slate','red'][i]}`} style={{width:`${count/Math.max(preview&&!filtered?60:rows.length,1)*100}%`}}/></div><b>{count}</b></div>;})}</div></div></Panel></div>
 {dialog && <InventoryItemDialog key={dialog.id || 'new'} record={dialog} farms={farms} blocks={blocks} items={items} preview={preview} saving={saving} onSave={save} onClose={()=>setDialog(null)} />}

 </div>;
}
