interface Env {
  LOCAL_TEST_LOGIN_ENABLED?: string;
  IDENTITY_ENABLED?: string;
  IDENTITY_RETURN_ORIGIN?: string;
  STRIPE_IDENTITY_SECRET_KEY?: string;
  PAYMENTS_ENABLED?: string;
  PAYMENT_RETURN_ORIGIN?: string;
  PAYSTACK_SECRET_KEY?: string;
  PAYSTACK_MERCHANT_COUNTRY?: string;
  PAYSTACK_CURRENCIES?: string;
  STRIPE_SECRET_KEY?: string;
  STRIPE_WEBHOOK_SECRET?: string;
  STRIPE_CURRENCIES?: string;
  PRIVATE_FILES_BACKUP: R2Bucket;
  TURNSTILE_SECRET_KEY: string;
  GOOGLE_CLIENT_ID: string;
  RESEND_API_KEY?: string;
  BOOTSTRAP_ADMIN_EMAILS?: string;
}
